### ISSUE TITLE
node_modules saved onto the repo

### ISSUE THREAD

**Issue by StevenRafferty** [Scott-Donaldson/BlacklistedWordsBot#14]
You shouldn't have the node_modules saved on the repository. for more info read this great article https://flaviocopes.com/should-commit-node-modules-git/

**Comment by StevenRafferty** [comment]
I've made a branch for this but I can't push, don't have permission.

**Comment by Scott-Donaldson** [comment]
Hey, I will look into the permission issue, as for the issue listed, I added node_modules to the .gitignore and removed them from the repo
